#!/bin/bash

####################################
#  HF  amplifier  fan  controller  #
#  for  PI2BOZ  10m  FM  repeater  #
#  V1.03rc2 by NL13716 / 19RF1292  #
####################################

#### Configuration
      pttpin=$(sed -n -e '/PTT_PIN/ s/.*\= *//p' /etc/svxlink/svxlink.conf | sed 's/gpio//')
      gpio=27          ## GPIO for fan relay
      startdelay=30    ## Wait x seconds before fan starts
      lagtime=5        ## Keep running for x minutes after transmittrer was turned off

### Initialize GPIO
  if [ ! -d /sys/class/gpio/gpio$gpio ]
then
    echo "$gpio" > /sys/class/gpio/export
    echo "out" > /sys/class/gpio/gpio$gpio/direction
  fi

#### Convert lagtime for timer
      timer=$((lagtime*60))

  while :
   do

### If PTT HIGH

  if [ "$(cat /sys/class/gpio/gpio$pttpin/value)" = "1" ]
   then
     sleep $startdelay
  if [ "$(cat /sys/class/gpio/gpio$pttpin/value)" = "1" ]
   then
    echo "1" > /sys/class/gpio/gpio$gpio/value
  fi

### If PTT LOW

  while :
   do
  if [ "$(cat /sys/class/gpio/gpio$pttpin/value)" = "0" ]
   then
      timer=$((timer-1))
  if [ "$timer" = "0" ]
   then
    echo "0" > /sys/class/gpio/gpio$gpio/value
     break
  fi

## If PTT HIGH again reset timer

  fi
     sleep 1
  if [ "$(cat /sys/class/gpio/gpio$pttpin/value)" = "1" ]
   then
      timer=$((lagtime*60))
  fi
  done
  fi

     sleep 0.1

  done
