#!/bin/bash 

#########################################################
#    Reads the  CPU speed  for the  SSH login screen    #
# (C)2022 NCBR | National CB Repeater | The Netherlands #
#########################################################

     cpuspeed=$(lscpu | grep "CPU max MHz" | sed 's/CPU max MHz//' | sed -r 's/^.{2}//')
     cpuspeed=$(calc $cpuspeed / 1000)
    echo $cpuspeed "GHz" > /etc/repeater/tmp/cpuspeed
