#!/bin/bash

#########################################################
#      Raeds   the   WAN  IP   Address   and   WAN      #
#      hostname   for   the   SSH   login   screen      #
# (C)2022 NCBR | National CB Repeater | The Netherlands #
#########################################################

     touch /etc/repeater/tmp/waniphost.fetch
     sleep 15

     wanip=$(curl -s ipinfo.io/ip)

  if [[ "$wanip" = *"404"* ]]
   then
    echo "Unable to detect" > /etc/repeater/tmp/wanip
    echo "Unable to detect" > /etc/repeater/tmp/wanhost
     rm /etc/repeater/tmp/waniphost.fetch
     exit
  fi

     wanhost=$(host $wanip)

  if [[ "$wanhost" == *"DOMAIN"* ]]
 then
      wanhost=$(echo $wanip)
    echo $wanip > /etc/repeater/wanip
    echo $wanhost > /etc/repeater/wanhost
     exit
  fi

    echo $wanip > /etc/repeater/tmp/wanip
    echo $(echo $wanhost | awk {'print $5'} | sed 's/.$//') > /etc/repeater/tmp/wanhost
     rm /etc/repeater/tmp/waniphost.fetch
