#!/bin/bash

#########################################################
#    Reads  the CPU model  for the  SSH login screen    #
# (C)2022 NCBR | National CB Repeater | The Netherlands #
#########################################################

     cpu=$(echo $(cat /proc/cpuinfo  | grep 'Hardware' | sed 's/Hardware//' | sed 's/://'))
    echo "$cpu" > /etc/repeater/tmp/cpumodel


