#!/bin/bash

####################################
#  Log  temperature  to  ramdrive  #
#  for  PI2BOZ  10m  FM  repeater  #
#  V1.04rc4 by NL13716 / 19RF1292  #
####################################

### Config

     pin=7                         ## Sensoir pin (NOT GPIO number!)
     logdir=/etc/ncbr/tmp/     ## Log directory
     tmpfile=temp                  ## Logfile for temperature value
     humfile=hum                   ## Logfile for humidity value
     mesint=2                      ## Measure interval in seconds
     fread=2                       ## Max. difference between readings to capture false readings

  while :
   do

### Get values from DHT22

     input=$(/opt/loldht $pin | grep "Temperature")
     hum=$(echo $input | cut -d " " -f3 | cut -c -4)
     temp=$(echo $input | cut -d " " -f7 | cut -c -4)
     lasttemp=$temp

## Capture false trigger | !! Test !!

     diff=$(calc $temp-$lasttemp | sed 's/..$//')
  if [ "$diff" != "" ]
   then
  if [ "$diff" -gt "$fread" ] || [ "$diff" -lt "$fread" ]
   then
     temp=$lasttemp
  fi
  fi

    ###

## Calibration

# Temperature
     offset=0.0
     dir=-
     temp=$(calc $temp $dir $offset)

# Humidity
     offset=0.0
     dir=-
     hum=$(calc $hum $dir $offset)

## Log values
    echo $hum > /$logdir/$humfile
    echo $temp > /$logdir/$tmpfile

      sleep $mesint

  done
