#!/bin/bash

####################################
#   Log temperature  &  humidity   #
#  for  PI2BOZ  10m  FM  repeater  #
#   V1.05f by NL13716 / 19RF1292   #
####################################

### Config

     logdir=/etc/repeater/tmp/     ## Log directory
     tmpfile=temp                  ## Logfile for temperature value
     humfile=hum                   ## Logfile for humidity value
     logint=15                     ## Measure interval in minutes

  while :
   do

### Get values from reading

     temp=$(cat $logdir$tmpfile)
     hum=$(cat $logdir$humfile)

    echo $(date +%A" "%d" "%B" "%Y" - "%H":"%M" | ""$temp""°C"" | "$hum"""%"" |") >> /var/log/temphum.log

      sleep $(calc $logint*60)

  done

