#!/bin/bash

####################################
#   RPi Shutdown & reboot switch   #
#  for  PI2BOZ  10m  FM  repeater  #
#  V1.04rc2 by NL13716 / 19RF1292  #
####################################

### Config
       switchgpio=22  ## GPIO pin for switch
       ledgpio=13     ## GPIO  pin for the LED

### Initialize GPIO
  if [ ! -d /sys/class/gpio/gpio$switchgpio ]
   then
    echo "$switchgpio" > /sys/class/gpio/export
    echo "in" > /sys/class/gpio/gpio$switchgpio/direction
  fi

  if [ ! -d /sys/class/gpio/gpio$ledgpio ]
   then
    echo "$ledgpio" > /sys/class/gpio/export
    echo "out" > /sys/class/gpio/gpio$ledgpio/direction
  fi

### Safe periode | Nothing will happen when the switch is only press shortly

  while :
   do
     sleep 1
       switch=$(cat /sys/class/gpio/gpio$switchgpio/value)
  if [  "$switch" = "1" ]
   then
       ((count=count+1))
  if [ "$count" = "4" ]
   then

### Pressing for reboot

  while :
   do
       switch=$(cat /sys/class/gpio/gpio$switchgpio/value)
  if [ "$switch" = "1" ]
   then
       ((count=count+1))
    echo 1 >/sys/class/gpio/gpio$ledgpio/value
      sleep 0.3
    echo 0 >/sys/class/gpio/gpio13/value
      sleep 0.3
  fi
  if [ "$switch" = "0" ]
   then
## >> reboot code here
    echo ""
    echo "Executing reboot command"
      sudo reboot
    echo ""
     sleep 3
     exit
  fi

### Pressing for shutdown

  if [ "$count" = "20" ]
   then
    echo 1 >/sys/class/gpio/gpio$ledgpio/value

## Wait for switch to be released

  while :
   do
       switch=$(cat /sys/class/gpio/gpio$switchgpio/value)
  if [ "$switch" = "0" ]
   then
## >> shutdown code here
    echo ""
    echo "Executing shutdown command"
      sudo shutdown now
    echo ""
     sleep 3
     exit
  fi
    sleep 0.3
  done
  fi
  done
  fi
  fi
  done
