#!/bin/bash

####################################
#    Raspberry   Pi    up   led    #
#  for  PI2BOZ  10m  FM  repeater  #
#   V1.05f by NL13716 / 19RF1292   #
####################################

### Config
      gpio=26

### Initialize GPIO
  if [ ! -d /sys/class/gpio/gpio$gpio ]
   then
    echo "$gpio" > /sys/class/gpio/export
    echo "out" > /sys/class/gpio/gpio$gpio/direction
  fi

### Turn Power LED ON
    echo "1" > /sys/class/gpio/gpio$gpio/value