#!/bin/bash

####################################
#    Raspberry   Pi    up   led    #
#  for  PI2BOZ  10m  FM  repeater  #
####################################

 . /etc/repeater/leds.conf

### Initialize GPIO
  if [ ! -d /sys/class/gpio/gpio$rpigpio ]
   then
    echo "$rpigpio" > /sys/class/gpio/export
    echo "out" > /sys/class/gpio/gpio$rpigpio/direction
  fi

### Turn Power LED oON
    echo "1" > /sys/class/gpio/gpio$rpigpio/value
