#!/bin/bash

#########################################################
#    Sets  the  GPIO  for  PTT  to  GPIO21  (pen 40)    #
# (C)2022 NCBR | National CB Repeater | The Netherlands #
#########################################################

sleep 1

    echo "21" > /sys/class/gpio/export
    echo "out" > /sys/class/gpio/gpio21/direction

#systemctl restart remotetrx
