#!/bin/bash

####################################
#        Squelch        led        #
#  for  PI2BOZ  10m  FM  repeater  #
#   V1.05f by NL13716 / 19RF1292   #
####################################

### Config
     ledgpio=12

### Initialize GPIO
  if [ ! -d /sys/class/gpio/gpio$ledgpio ]
   then
    echo "$ledgpio" > /sys/class/gpio/export
    echo "out" > /sys/class/gpio/gpio$ledgpio/direction
  fi

### Led state on script start

    echo "0" > /sys/class/gpio/gpio$ledgpio/value
   
      tail -f -n3 /var/log/remotetrx | grep -q "The squelch is OPEN"
    echo "1" > /sys/class/gpio/gpio$ledgpio/value
  
      tail -f -n0 /var/log/remotetrx | grep -q "The squelch is CLOSED"
    echo "0" > /sys/class/gpio/gpio$ledgpio/value
  
### Led control

  while :
  do

## If squelch is open

      tail -f -n0 /var/log/remotetrx | grep -q "The squelch is OPEN"
    echo "1" > /sys/class/gpio/gpio$ledgpio/value
 
## If squelchg is closed

     tail -f -n0 /var/log/remotetrx | grep -q "The squelch is CLOSED"
    echo "0" > /sys/class/gpio/gpio$ledgpio/value

     sleep 0.1

  done
