#!/bin/bash

####################################
#         TX           LED         #
#  for  PI2BOZ  10m  FM  repeater  #
####################################


     pttgpio=$(sed -n -e '/PTT_PIN/ s/.*\= *//p' /etc/svxlink/svxlink.conf | sed 's/gpio//')

 . /etc/repeater/leds.conf

### Initialize GPIO
  if [ ! -d /sys/class/gpio/gpio$txgpio ]
   then
    echo "$txgpio" > /sys/class/gpio/export
    echo "out" > /sys/class/gpio/gpio$txgpio/direction
  fi

  while :
   do

### If TX is ON
     txon=$(cat /sys/class/gpio/gpio$pttgpio/value)
  if [ $txon = "1" ]
   then

## If not already ON
  if [ "$tx" != "alreadyon" ]
   then
    echo "1" > /sys/class/gpio/gpio$txgpio/value
     tx="alreadyon"
  fi
  fi

### If TX is OFF
     txon=$(cat /sys/class/gpio/gpio21/value)
  if [ $txon =  "0" ]
   then

## If not already OFF
  if [ "$tx" != "alreadyoff" ]
   then
   echo "0" > /sys/class/gpio/gpio$txgpio/value
     tx="alreadyoff"
  fi
  fi
      sleep 0.1

  done
