#!/bin/bash

####################################
#       TX      UP       LED       #
#  for  PI2BOZ  10m  FM  repeater  #
####################################

### Config
     hst=10.3.0.7        ## IP address of host to ping
     to=1                ## Ping can take this long before it fails
     t=1                 ## Number of pings
     int=60              ## Check interval in seconds
     gpio=19             ## GPIO for LED

### Set GPIO
  if [ "$(cat /sys/class/gpio/gpio$gpio/value)" != "0" ] && [ "$(cat /sys/class/gpio/gpio$gpio/value)" != "1" ]
   then
    echo "$gpio" > /sys/class/gpio/export
    echo "out" > /sys/class/gpio/gpio$gpio/direction
  fi

  while :
   do

## Ping host
  if ping -c$t -w$to $hst >/dev/null 2>&1
   then

## If UP

  if [ "$(cat /sys/class/gpio/gpio$gpio/value)" = "0" ]
   then
    echo "RX is UP"  >&2
    echo "1" > /sys/class/gpio/gpio$gpio/value
  fi

  else

## If DOWN

  if [ "$(cat /sys/class/gpio/gpio$gpio/value)" = "1" ]
   then
    echo "RX is DOWN" >&2
    echo "0" > /sys/class/gpio/gpio$gpio/value
  fi

  fi

      sleep $int

  done
